# Generated by Django 5.0.7 on 2024-07-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_post_date_post_dead_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dead_line',
            new_name='deadline',
        ),
    ]
